insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330976','Carlos Andrés','Acosta Zúñiga','full_name','carlos.acosta@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335109','Luis Gilbert','Acuña Flores','full_name','luis.acuna@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335865','Alejandro José','Almendárez Lacayo','full_name','alejandro.almendarez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081337362','Gabriel Alexander','Alvarenga','full_name','gabriel.alvarenga@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('069256280','Juan Augusto','Angeles Quevedo','full_name','juan.angeles@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336324','José Antonio','Ardón Gutiérrez','full_name','jose.ardon@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335586','Sergio Abraham','Argueta Juárez','full_name','sergio.argueta@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081337822','Cristina Elizabeth','Arindia Cordero','full_name','cristina.arindia@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335905','Eliberth Donavic','Ascue Pallqui','full_name','eliberth.ascue@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081337875','Mercy Lorena','Ayala Rivera','full_name','mercy.ayala@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('065230819','Verónica Lucía','Benalcázar Sandoval','full_name','veronica.benalcazar@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081337817','Andrea Carolina','Bonilla Medina','full_name','andrea.bonilla@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335784','Arnoldo ','Brenes Simon','full_name','arnoldo.brenes@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335609','David','Burneo','full_name','david.burneo@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081334341','Josué Jesús','Cabrera Ruilova','full_name','josue.cabrera@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('056533118','Marlon Abercio','Cañas Enamorado','full_name','marlon.canase@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081331070','Yasnary Missiel','Castellanos Betancourth','full_name','yasnary.castellanos@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('051608059','Enaida del Carmen','Castillo De Gracia','full_name','enaida.castillo@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330145','Virgie Marie','Castro-Conde Agüero','full_name','virgie.castro@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336179','Juan Martin','Cazenave Serratti','full_name','juan.cazenave@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081337587','Efraín','Chacón Buendía','full_name','efrain.chacon@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081333538','Noel','Chamorro Tijerino','full_name','noel.chamorro@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('054305028','José Luis','Chávez Montoya','full_name','josel.chavez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335364','Roberto','Chiclote Valdivia','full_name','roberto.chiclote@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('052264726','Laura Melissa','Colindres Flores','full_name','laura.colindres@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081334314','Dennis André','Concha Sierralta','full_name','dennis.concha@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336305','Elsy Yesenia','Cordero Mejia','full_name','elsy.cordero@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081338152','José Fernando','De Gracia Santamaria','full_name','jose.degracia@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330183','Eduardo Miguel','De Mena Ruffo','full_name','eduardo.demenaruffo@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330196','Dulce María','Duarte','full_name','dulce.duarte@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('033964361','Juan Carlos','Estrada Rivera','full_name','juan.estrada@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081333825','José Angel','Flamenco Francés','full_name','jose.flamenco@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081338157','Guerald Eduardo','Flores Hurtado','full_name','guerald.flores@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081334768','Leymer Ivan','Garzón Castillo','full_name','leymer.garzon@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081332672','Roderick Orestes','González Caballero','full_name','roderick.gonzalez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335531','Alex Horacio','González Murillo','full_name','alex.gonzalez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081334678','Andrés Alberto','Guzmán Herrera','full_name','andres.guzman@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('006272302','Félix Magdiel','Hernández Castillo','full_name','felix.hernandez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336656','Joshua Alexander','Hernández Panduro','full_name','joshua.hernandez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('018636842','Andrea Polet','Herrera Bucheli','full_name','polet.herrera@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335075','Daniel Paul','Hidalgo Cevallos','full_name','daniel.hidalgo@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('037638872','Miguel Antonio','Juarez Illescas','full_name','miguel.juarez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081334002','Fiorella','Lazo Antonio','full_name','fiorella.lazo@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081333477','Luisa Fernanda','López Cuellar','full_name','luisa.lopez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('000210738','Robín Alejandro','López Mayorquin','full_name','robin.lopez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('073004068','Andrea Michelle','López Rosa','full_name','andrea.lopez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081333325','Josué Alejandro','Mejía Fernández','full_name','josue.mejia@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330642','Ángel Santos','Mendieta Barrios','full_name','angel.mendieta@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335631','Milagros Raquel','Muñoz Tenorio','full_name','milagros.munoz@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('054320309','Baggda','Nolasco Fuentes','full_name','baggda.nolasco@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336538','Angel Virgilio','Ochoa Castillo','full_name','angel.ochoa@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('051729943','Óscar David','Ochoa Fernández','full_name','oscar.ochoa@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336755','Juan Carlos','Ochoa Rodríguez','full_name','juan.ochoa@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336274','Mariana Milagros','Ordinola Macha','full_name','mariana.ordinola@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('000887472','Adriana','Ortiz Flamenco','full_name','adriana.ortizf@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330606','Andrea','Oyanguren Cortijo','full_name','andrea.oyanguren@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081332067','Jesús Josué','Pacheco Brizuela','full_name','jesus.pacheco@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081333390','Felix Alberto','Perez Fumarola','full_name','felix.perez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336775','José Miguel','Quirós Montoya','full_name','jose.quirosm@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('031157916','Jesús Alberto','Ramírez Costales','full_name','jesus.ramirez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081330963','Eduardo José','Ramírez Díaz','full_name','eduardo.ramirez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081332743','Ramiro Alejandro','Rodas Gutiérrez','full_name','ramiro.rodas@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335594','Juan Esteban','Rojas Soto','full_name','juan.rojass@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081338134','Joan','Rosell Zevallos','full_name','joan.zevallos@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('068743753','Jaime Manolo','Samayoa González','full_name','jaime.samayoa@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081337917','Roberto Andrés','Samayoa Morales','full_name','roberto.samayoa@mba2019.incae.edu>','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081335894','Ignacio Alejandro','Sandí Fonseca','full_name','ignacio.sandi@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081336644','Luis Alfonso','Serrano Ayon','full_name','luis.serrano@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('058629894','Italo Cesar','Sosa Hernández','full_name','italo.sosa@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('073390311','María de los Ángeles','Torres Rodríguez','full_name','maria.torres@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('079375526','Christian Adrian','Urroz Reyes','full_name','christian.urroz@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('061037493','Lucía Carolina','Urrutia Hurtado','full_name','lucia.urrutia@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('057470510','Héctor José','Velásquez Moreno','full_name','hector.velasquez@mba2019.incae.edu','000');
insert into user (incae_id, first_name,last_name,full_name,email,password) values ('081338185','Leonardo','Velásquez Torres','full_name','leonardo.velasquez@mba2019.incae.edu','000');